name: stock_demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.4.3+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/stock_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
   
flutter:
  uses-material-design: true

  assets:
    - assets/
     